
.PHONEY:
init:
	pipenv shell

.PHONEY:
lint:
	black .

.PHONEY:
requirements:
	echo "# Requirements generated from Pipfile, do not edit this file directly" > requirements.txt
	pipenv requirements >> requirements.txt

.PHONY:
tests:
	mkdir -p ./tmp/pynguin-results
	pynguin --project-path ./sqlalchemy2atlas --output-path ./tmp/pynguin-results --module-name sqlalchemy2atlas
