name: Bump version
on:
  pull_request:
    types: [closed]
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: ^main$
          pre_release_branches: ^release\/.*$ # e.g. release/my-release-candidate

      - name: "Show outputs (Optional)"
        shell: bash
        run: |
          echo 'New Tag: ${{ steps.tag-version.outputs.new_tag }}'
          echo 'New Version: ${{ steps.tag-version.outputs.new_version }}'
          echo 'Old Tag: ${{ steps.tag-version.outputs.previous_tag }}'
          echo 'Old Version: ${{ steps.tag-version.outputs.previous_version }}'
          echo 'Release Type: ${{ steps.tag-version.outputs.release_type }}'
          echo 'Changelog: ${{ steps.tag-version.outputs.changelog }}'
