name: Python package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install AtlasGO
        run: |
          curl -LO https://release.ariga.io/atlas/atlas-linux-amd64-latest
          sudo install -o root -g root -m 0755 ./atlas-linux-amd64-latest /usr/local/bin/atlas
      - name: Test with pytest
        run: |
          pytest
